# Generated by Django 5.1.2 on 2024-10-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('C', 'Cancelado'), ('P', 'Pendente'), ('F', 'Finalizado')], default='P', max_length=1),
        ),
    ]
